### ISSUE TITLE
兄弟，你这个手机端能适配吗

### ISSUE THREAD

**Issue by alinnnnnnnnn** [weiqinke/react-admin-nest#1]
手机上切换不了菜单，没法看呀。电脑上能看，就是配色不好看，有切换主题的配置吗？

**Comment by weiqinke** [comment]
谢谢您的建议，我还没做切换主题的功能，预计会和手机适配一起上线，暂时归类到美化工作。

**Comment by weiqinke** [comment]
此功能已在2021/03/25号上线。
